<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
    <Title>hotia!resources</Title>
    <Product>hotia!resources</Product>
    <Company>moorf</Company>
  </PropertyGroup>
  <PropertyGroup Label="Nuget">
    <Title>hotia!resources</Title>
    <PackageId>moorf.hotia.Game.Resources</PackageId>
    <Authors>moorf</Authors>
    <PackageLicenseUrl>https://github.com/ppy/osu-resources/blob/master/LICENCE.md</PackageLicenseUrl>
    <PackageProjectUrl>https://github.com/ppy/osu-resources</PackageProjectUrl>
    <RepositoryUrl>https://github.com/ppy/osu-resources</RepositoryUrl>
    <PackageReleaseNotes>Automated release.</PackageReleaseNotes>
    <copyright>Copyright (c) 2019 ppy Pty Ltd</copyright>
    <PackageTags>hotia game resources</PackageTags>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Beatmaps\**\*" />
    <EmbeddedResource Include="Fonts\**\*" />
    <EmbeddedResource Include="Samples\**\*" />
    <EmbeddedResource Include="Skins\**\*" />
    <EmbeddedResource Include="Shaders\**\*" />
    <EmbeddedResource Include="Textures\**\*" />
    <EmbeddedResource Include="Tracks\**\*" />
  </ItemGroup>
  <ItemGroup>
    <!-- Resolves references to LocalisableString. -->
    <!-- <PackageReference Include="ppy.osu.Framework" Version="2021.611.0"> -->
      <!-- <PrivateAssets>all</PrivateAssets> -->
    <!-- </PackageReference> -->
	<ProjectReference Include="..\..\hotia-framework\osu.Framework\osu.Framework.csproj" />
  </ItemGroup>
</Project>